### PR TITLE
Rename update.py to updater.py

### PR DESCRIPTION
**Pull request by LEGENDXOP**

### CODE REVIEW

**Comment by LEGENDXOP** [comment]
Name change

**Comment by LEGENDXOP** [comment]
You ready i give you both pull requests bcz i am free and i help you

**Comment by rohithaditya** [comment]
cant name error would come sur

**Comment by rohithaditya** [comment]
sorry sur

**Comment by LEGENDXOP** [comment]
Abe bsdk updater.py hota h chutie 😤😤

**Pull request closed without merging**
